# Part 9 -- Predictive Modeling

Prepare data for **Singular Value Decomposition (SVD)**.

### Load lib codes:

In [1]:
!pwd

/home/jovyan/work/Portfolio/predicting_stock_market_trends_with_Twitter/ipynb


In [2]:
from os import chdir
chdir('/home/jovyan/work/Portfolio/predicting_stock_market_trends_with_Twitter/')

from lib import *
from lib.twitter_keys import my_keys
# suppress_warnings()
%matplotlib inline
from sklearn.externals import joblib

In [5]:
X_tfidf_10000 = joblib.load('../predicting_stock_market_trends_with_Twitter/data/X_tfidf_10000.pickle')

In [6]:
X_tfidf = joblib.load('../predicting_stock_market_trends_with_Twitter/data/X_tfidf.pickle')

# DO IT ON RAW DATA --> TFIDF TO LOGISTIC REGRESSION --> GRIDSEARCH TUNE LOG REG & TRY RF, SVC, KNN.

* THEN do a GridSearch on the best one
* THEN CIRCLE BCAK AND EDA ON CLUSTERS

## Logistic Regression

In [7]:
from sklearn.model_selection import GridSearchCV, ShuffleSplit
from sklearn.linear_model import LogisticRegression

In [17]:
X = joblib.load('../predicting_stock_market_trends_with_Twitter/data/X_tfidf.pickle')

In [26]:
y = joblib.load('../predicting_stock_market_trends_with_Twitter/data/y_AAPL_le.pickle')

In [22]:
X.shape

(68006, 5268)

In [27]:
y.shape

(68006,)

In [30]:
lr = LogisticRegression()
lr.fit(X, y)

print('Logreg intercept:', lr.intercept_)
print('Logreg coef(s):', lr.coef_)
print('Logreg predicted probabilities:', lr.predict_proba(X[0:5,:]))

Logreg intercept: [ 2.29679909 -2.63650072 -3.71046044]
Logreg coef(s): [[-0.1096753   0.1179682   0.11222695 ..., -0.70791925  0.25322048
   0.72242858]
 [-0.14108511 -0.23570642 -0.2716486  ...,  0.99141145  0.00489344
  -0.45665065]
 [ 0.40972848  0.0263229   0.2050937  ..., -0.24414754 -0.30774031
  -0.41885802]]
Logreg predicted probabilities: [[ 0.9544442   0.02200659  0.02354921]
 [ 0.9529399   0.03619128  0.01086882]
 [ 0.87380439  0.06853616  0.05765945]
 [ 0.92790362  0.04227912  0.02981726]
 [ 0.85095723  0.12496628  0.02407649]]


In [38]:
params = {
    'penalty':['l2','l1'],
#     'C':np.logspace(-3,3,30)
    'C': np.logspace(-10,10)
}

In [39]:
gs_lr = GridSearchCV(LogisticRegression(random_state=42, n_jobs=-1), param_grid=params, n_jobs=-1,cv=5 )

In [41]:
gs_lr.fit(X,y)

KeyboardInterrupt: 

In [ ]:
gs_lr.best_estimator_

In [ ]:
results = pd.DataFrame(gs_lr.cv_results_)
results[results['rank_test_score'] < 5].T

In [37]:
print('coefs:', gs_lr.best_estimator_.coef_)
print('beta_0:', gs_lr.best_estimator_.intercept_)

coefs: [[  6.12237082e-05   7.78718446e-03   6.53435492e-04 ...,  -7.88262938e-04
    6.19739796e-04   2.03016430e-03]
 [ -1.22517049e-03  -7.78286572e-03  -9.19391454e-04 ...,   1.01781648e-03
   -3.31579171e-04  -1.51958077e-03]
 [ -2.56685405e-04  -8.52972003e-03  -3.30358475e-04 ...,  -6.17346687e-04
   -7.77128287e-04  -2.10531349e-03]]
beta_0: [ 1.89966506 -2.14074555 -2.62323043]
